# Base image with Python
FROM python:3.11-slim

# Install system dependencies (e.g., for image handling or other tools)
RUN apt-get update && apt-get install -y \
    libzbar0 \
    libzbar-dev \
    build-essential \
    gcc \
    zlib1g-dev \
    libjpeg-dev \
    && rm -rf /var/lib/apt/lists/*

# Set work directory in the container
WORKDIR /app

# Copy and install dependencies
COPY requirements.txt .
RUN pip install --upgrade pip && pip install -r requirements.txt

# Copy app code into the container
COPY . .

# Collect static files and run migrations
RUN python manage.py collectstatic --noinput && python manage.py migrate

# Run the app using Gunicorn
CMD ["gunicorn", "EventsHub.wsgi:application", "--bind", "0.0.0.0:8000"]
