# Use official Python base image
FROM python:3.11-slim

# Install required system packages
RUN apt-get update && apt-get install -y \
    build-essential \
    && rm -rf /var/lib/apt/lists/*

# Set work directory
WORKDIR /app

# Install dependencies
COPY requirements.txt .
RUN pip install --upgrade pip && pip install -r requirements.txt

# Copy project files
COPY . .

# Set environment variables
ENV PYTHONUNBUFFERED=1

# Collect static files and run DB migrations
RUN python manage.py collectstatic --noinput && \
    python manage.py migrate && \
    echo "from django.contrib.auth import get_user_model; \
          User = get_user_model(); \
          User.objects.filter(username='admin').exists() or \
          User.objects.create_superuser('admin', 'admin@example.com', 'adminpass123')" \
          | python manage.py shell

# Start Gunicorn server
CMD gunicorn EventsHub.wsgi:application --bind 0.0.0.0:8000
