# Base image with Python
FROM python:3.11-slim

# Install zbar and build tools
RUN apt-get update && apt-get install -y \
    libzbar0 \
    libzbar-dev \
    build-essential \
    gcc \
    zlib1g-dev \
    libjpeg-dev \
    && rm -rf /var/lib/apt/lists/*

# Set work directory
WORKDIR /app

# Install dependencies
COPY requirements.txt .
RUN pip install --upgrade pip && pip install -r requirements.txt

# Copy app code
COPY . .

# Collect static, run migrations
RUN python manage.py collectstatic --noinput && \
    python manage.py migrate

# Run the app
CMD ["gunicorn", "EventsHub.wsgi:application", "--bind", "0.0.0.0:8000"]
