app = "event-hub-yorlsg"

[build]
  dockerfile = "DockerFile"

[env]
  FLY_REGION = "sin"
  SECRET_KEY = django-insecure-!albcnc1@u-)emu&6xgtsoi12xl97u93kuc+7-wu5txubd1b*^  # Set this to a secure key in production

[[mounts]]
  source = "data"
  destination = "/data"

[[services]]
  internal_port = 8000  # Port where your app will run

  [services.http_checks]
    interval = 10000
    grace_period = "5s"
    method = "GET"
    path = "/health"

[scale]
  vm_size = "shared-cpu-1x"
  count = 1  # Number of instances

[[logging]]
  type = "stdout"
