# Generated by Django 4.2.1 on 2025-04-16 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0004_event_highlights_eventface'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='highlights',
        ),
        migrations.AddField(
            model_name='event',
            name='capacity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='EventHighlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='highlights', to='MainApp.event')),
            ],
        ),
    ]
