# Generated by Django 4.2.1 on 2025-04-19 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0007_remove_userprofile_avatar_useravatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='map_link',
            field=models.TextField(blank=True, null=True),
        ),
    ]
