# Generated by Django 4.2.1 on 2025-04-24 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0010_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='carousel_image_1',
            field=models.ImageField(blank=True, null=True, upload_to='carousel_images/'),
        ),
        migrations.AddField(
            model_name='event',
            name='carousel_image_2',
            field=models.ImageField(blank=True, null=True, upload_to='carousel_images/'),
        ),
        migrations.AddField(
            model_name='event',
            name='carousel_image_3',
            field=models.ImageField(blank=True, null=True, upload_to='carousel_images/'),
        ),
        migrations.AddField(
            model_name='event',
            name='carousel_image_4',
            field=models.ImageField(blank=True, null=True, upload_to='carousel_images/'),
        ),
    ]
