# Generated by Django 4.2.1 on 2025-04-25 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0012_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_redeemed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='redeemed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
