# Generated by Django 4.2.1 on 2025-04-28 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0014_order_qr_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_sales', to='MainApp.event')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='MainApp.tickettype')),
            ],
        ),
    ]
