# Generated by Django 4.2.1 on 2025-05-02 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0015_ticketsale'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('Concerts', 'Concert'), ('Technology', 'Technology'), ('Food & Drink', 'Food & Drink'), ('Sports & Fitness', 'Sports & Fitness'), ('Education & Career', 'Education & Career'), ('Arts & Creativity', 'Arts & Creativity'), ('Entertainment & Culture', 'Entertainment & Culture')], default='Concerts', max_length=50),
        ),
    ]
