name: Deploy Django App to Fly.io

on:
  push:
    branches:
      - main  # Trigger the action on pushes to the 'main' branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # Check out the repository code to the GitHub runner

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2  # Set up Docker buildx to build the image

    - name: Log in to Fly.io
      uses: superfly/flyctl-action@v1  # Log into Fly.io using the Fly API token
      with:
        api_token: ${{ secrets.FLY_API_TOKEN }}  # Fetch Fly.io API token from GitHub Secrets

    - name: Build Docker image
      run: |
        docker build -t event-hub-yorlsg .  # Build Docker image for your app

    - name: Push Docker image to Fly.io
      run: |
        flyctl deploy --image event-hub-yorlsg --app event-hub-yorlsg  # Push the image to Fly.io

    - name: Run migrations and collect static files
      run: |
        flyctl ssh console --command "python manage.py migrate && python manage.py collectstatic --noinput"  # Run migrations and collect static files
